<?php

namespace Database\Seeders;

use App\Models\Application;
use App\Models\Cohort;
use Illuminate\Database\Seeder;

class ApplicationSeeder extends Seeder
{
    public function run(): void
    {
        $upcomingCohort  = Cohort::where('status', 'upcoming')->orderBy('sort_order')->first();
        $upcomingCohort2 = Cohort::where('status', 'upcoming')->orderBy('sort_order')->skip(1)->first();

        $rows = [
            [
                'first_name'   => 'James',
                'last_name'    => 'Okonkwo',
                'email'        => 'james.okonkwo@example.com',
                'phone'        => '+234 803 000 0001',
                'program_slug' => 'advanced-data-analytics',
                'cohort_id'    => $upcomingCohort?->id,
                'experience'   => 'none',
                'why'          => 'I want to transition from my accounting role into a data career. Numbers have always made sense to me, and I want to do more with them.',
                'status'       => 'received',
            ],
            [
                'first_name'   => 'Nkechi',
                'last_name'    => 'Adeyemi',
                'email'        => 'nkechi.adeyemi@example.com',
                'phone'        => '+234 806 000 0002',
                'program_slug' => 'business-data-analyst',
                'cohort_id'    => $upcomingCohort?->id,
                'experience'   => 'some',
                'why'          => 'I have used Excel in my current role but want to go deeper with analytics and eventually move into a proper data analyst position.',
                'status'       => 'reviewing',
            ],
            [
                'first_name'   => 'Emmanuel',
                'last_name'    => 'Bello',
                'email'        => 'emmanuel.bello@example.com',
                'phone'        => null,
                'program_slug' => 'python-r-for-data-science',
                'cohort_id'    => $upcomingCohort?->id,
                'experience'   => 'some',
                'why'          => 'I studied statistics in school and have some Python knowledge. I want to bridge the gap into professional data science.',
                'status'       => 'interview',
            ],
            [
                'first_name'   => 'Fatimah',
                'last_name'    => 'Yusuf',
                'email'        => 'fatimah.yusuf@example.com',
                'phone'        => '+234 701 000 0004',
                'program_slug' => 'sql-for-data-analytics',
                'cohort_id'    => $upcomingCohort?->id,
                'experience'   => 'none',
                'why'          => 'I am a fresh graduate looking to start a career in tech. SQL seems like the most practical first step.',
                'status'       => 'accepted',
            ],
            [
                'first_name'   => 'Chukwudi',
                'last_name'    => 'Eze',
                'email'        => 'chukwudi.eze@example.com',
                'phone'        => '+234 803 000 0005',
                'program_slug' => 'business-intelligence-with-power-bi',
                'cohort_id'    => $upcomingCohort2?->id,
                'experience'   => 'none',
                'why'          => 'My company uses Power BI but no one really knows how to use it well. I want to be the person who changes that.',
                'status'       => 'accepted',
            ],
            [
                'first_name'   => 'Adaeze',
                'last_name'    => 'Obi',
                'email'        => 'adaeze.obi@example.com',
                'phone'        => null,
                'program_slug' => 'business-intelligence-with-tableau',
                'cohort_id'    => $upcomingCohort2?->id,
                'experience'   => 'a_lot',
                'why'          => 'I am a senior marketing manager and want to own my own data rather than waiting on analysts. Tableau looks like the right tool.',
                'status'       => 'declined',
            ],
            [
                'first_name'   => 'Tunde',
                'last_name'    => 'Fashola',
                'email'        => 'tunde.fashola@example.com',
                'phone'        => '+234 806 000 0007',
                'program_slug' => 'data-analytics-for-beginners',
                'cohort_id'    => $upcomingCohort?->id,
                'experience'   => 'none',
                'why'          => 'I have no background at all but I am hardworking and motivated. I just need someone to give me a proper start.',
                'status'       => 'received',
            ],
            [
                'first_name'   => 'Blessing',
                'last_name'    => 'Nwosu',
                'email'        => 'blessing.nwosu@example.com',
                'phone'        => '+234 701 000 0008',
                'program_slug' => 'healthcare-data-analyst',
                'cohort_id'    => $upcomingCohort2?->id,
                'experience'   => 'some',
                'why'          => 'I am a nurse with 5 years of experience and I see how better data analysis could improve patient care in our ward.',
                'status'       => 'reviewing',
            ],
            [
                'first_name'   => 'Obiora',
                'last_name'    => 'Nwankwo',
                'email'        => 'obiora.nwankwo@example.com',
                'phone'        => null,
                'program_slug' => 'introduction-to-artificial-intelligence',
                'cohort_id'    => null,
                'experience'   => 'some',
                'why'          => 'AI is everywhere and I want to understand it properly, not just the hype. This course seems grounded in practical knowledge.',
                'status'       => 'received',
            ],
            [
                'first_name'   => 'Chioma',
                'last_name'    => 'Amaechi',
                'email'        => 'chioma.amaechi@example.com',
                'phone'        => '+234 803 000 0010',
                'program_slug' => 'the-complete-sql-certification-course',
                'cohort_id'    => $upcomingCohort2?->id,
                'experience'   => 'none',
                'why'          => 'I want a certification that employers actually recognise. SQL feels like a foundational skill I cannot afford to skip.',
                'status'       => 'interview',
            ],
            [
                'first_name'   => 'Kelechi',
                'last_name'    => 'Ihejirika',
                'email'        => 'kelechi.ihejirika@example.com',
                'phone'        => '+234 806 000 0011',
                'program_slug' => 'data-analytics-with-excel',
                'cohort_id'    => null,
                'experience'   => 'none',
                'why'          => 'I use Excel every day at work but only the basics. I want to master it before moving on to bigger tools.',
                'status'       => 'received',
            ],
            [
                'first_name'   => 'Adeola',
                'last_name'    => 'Bakare',
                'email'        => 'adeola.bakare@example.com',
                'phone'        => '+234 701 000 0012',
                'program_slug' => 'foundation-to-data-analytics',
                'cohort_id'    => $upcomingCohort?->id,
                'experience'   => 'none',
                'why'          => 'I am returning to work after three years raising children. This feels like the right moment to learn something new and future-proof.',
                'status'       => 'accepted',
            ],
            [
                'first_name'   => 'Seun',
                'last_name'    => 'Adeleke',
                'email'        => 'seun.adeleke@example.com',
                'phone'        => null,
                'program_slug' => 'foundational-data-analytics',
                'cohort_id'    => $upcomingCohort?->id,
                'experience'   => 'none',
                'why'          => 'A colleague of mine completed this program and landed a job within two months. That is enough proof for me.',
                'status'       => 'reviewing',
            ],
            [
                'first_name'   => 'Ngozi',
                'last_name'    => 'Okafor',
                'email'        => 'ngozi.okafor@example.com',
                'phone'        => '+234 803 000 0014',
                'program_slug' => 'data-analysis-for-business-professionals',
                'cohort_id'    => $upcomingCohort2?->id,
                'experience'   => 'a_lot',
                'why'          => 'I run a team of 12 at a FMCG company. I need to understand our data well enough to make faster, smarter decisions without always relying on the BI team.',
                'status'       => 'accepted',
            ],
            [
                'first_name'   => 'Uche',
                'last_name'    => 'Okonkwo',
                'email'        => 'uche.okonkwo@example.com',
                'phone'        => '+234 806 000 0015',
                'program_slug' => 'summer-bootcamp',
                'cohort_id'    => null,
                'experience'   => 'none',
                'why'          => 'I have the whole summer free and want to use it productively. A bootcamp format suits my learning style.',
                'status'       => 'declined',
            ],
            [
                'first_name'   => 'Miriam',
                'last_name'    => 'Danjuma',
                'email'        => 'miriam.danjuma@example.com',
                'phone'        => '+234 701 000 0016',
                'program_slug' => 'the-business-analyst-training',
                'cohort_id'    => $upcomingCohort2?->id,
                'experience'   => 'some',
                'why'          => 'I have been working in operations and want to formalise my skills as a business analyst. I need the structured training.',
                'status'       => 'interview',
            ],
            [
                'first_name'   => 'Chibuzor',
                'last_name'    => 'Ani',
                'email'        => 'chibuzor.ani@example.com',
                'phone'        => null,
                'program_slug' => 'data-analytics-with-excel-nysc',
                'cohort_id'    => null,
                'experience'   => 'none',
                'why'          => 'I am currently serving and want to use this period to build a skill set I can deploy immediately after service.',
                'status'       => 'received',
            ],
            [
                'first_name'   => 'Aisha',
                'last_name'    => 'Garba',
                'email'        => 'aisha.garba@example.com',
                'phone'        => '+234 803 000 0018',
                'program_slug' => 'advanced-data-analytics',
                'cohort_id'    => $upcomingCohort?->id,
                'experience'   => 'a_lot',
                'why'          => 'I already work as a data analyst but feel I have plateaued. I want the advanced track to push me to the next level.',
                'status'       => 'accepted',
            ],
            [
                'first_name'   => 'Emeka',
                'last_name'    => 'Onwudiwe',
                'email'        => 'emeka.onwudiwe@example.com',
                'phone'        => '+234 806 000 0019',
                'program_slug' => 'unsure',
                'cohort_id'    => null,
                'experience'   => 'none',
                'why'          => 'I know I want to get into tech but I am not sure which direction yet. I am hoping the admissions conversation will help me figure that out.',
                'status'       => 'received',
            ],
            [
                'first_name'   => 'Tolulope',
                'last_name'    => 'Adesanya',
                'email'        => 'tolulope.adesanya@example.com',
                'phone'        => '+234 701 000 0020',
                'program_slug' => 'python-r-for-data-science',
                'cohort_id'    => $upcomingCohort2?->id,
                'experience'   => 'some',
                'why'          => 'I have been self-teaching Python for six months but need a structured programme with mentorship to truly progress.',
                'status'       => 'reviewing',
            ],
        ];

        foreach ($rows as $row) {
            Application::updateOrCreate(
                ['email' => $row['email'], 'program_slug' => $row['program_slug']],
                $row
            );
        }
    }
}
